CREATE SCHEMA IF NOT EXISTS core AUTHORIZATION ayush;
CREATE SCHEMA IF NOT EXISTS secure AUTHORIZATION ayush;
CREATE SCHEMA IF NOT EXISTS icon_packs AUTHORIZATION ayush;
CREATE SCHEMA IF NOT EXISTS icon_requests AUTHORIZATION ayush;