consumes:
- application/json
definitions:
  Billing:
    description: Billing is the junction type of User and Plan
    properties:
      dev_id:
        description: ID of the associated developer
        example: 3
        format: int64
        type: integer
        x-go-name: DevID
      plan_id:
        description: ID of the plan being billed
        example: 1
        format: int64
        type: integer
        x-go-name: PlanID
    type: object
    x-go-package: github.com/PrunedNeuron/Fluoride/pkg/model
  DevRequest:
    description: DevRequest is the developer request body
    properties:
      email:
        description: email address of the developer
        example: jdoe@gmail.com
        type: string
        x-go-name: Email
      name:
        description: name of the developer
        example: John Doe
        type: string
        x-go-name: Name
      role:
        description: status of the request
        example: success
        type: string
        x-go-name: Role
      url:
        description: website of the developer
        example: https://ayushm.dev
        type: string
        x-go-name: URL
      username:
        description: username of the developer
        example: jdoe
        type: string
        x-go-name: Username
    type: object
    x-go-package: github.com/PrunedNeuron/Fluoride/docs/swagger
  Icon:
    description: Icon is the icon request type
    properties:
      component:
        description: App component
        example: com.canva.editor/com.canva.app.editor.splash.SplashActivity
        type: string
        x-go-name: Component
      created_at:
        description: Date created at
        example: "2020-09-17T03:07:13.418204+05:30"
        format: date-time
        type: string
        x-go-name: CreatedAt
      id:
        description: Icon request ID
        example: 51
        format: int64
        type: integer
        x-go-name: ID
      name:
        description: App name
        example: Canva
        type: string
        x-go-name: Name
      pack:
        description: Name of the  Icon pack it belongs to
        example: Valacons
        type: string
        x-go-name: Pack
      requesters:
        description: Number of requesters
        example: 28
        format: int64
        type: integer
        x-go-name: Requesters
      status:
        description: Status of request (pending / complete)
        example: pending
        type: string
        x-go-name: Status
      updated_at:
        description: Date updated at
        example: "2020-09-17T03:07:13.418204+05:30"
        format: date-time
        type: string
        x-go-name: UpdatedAt
      url:
        description: Play Store URL (may be autogenerated)
        example: https://play.google.com/store/apps/details?id=com.canva.editor
        type: string
        x-go-name: URL
    type: object
    x-go-package: github.com/PrunedNeuron/Fluoride/pkg/model
  IconResponse:
    description: IconResponse is the developer response
    properties:
      icons:
        description: the list of icons
        items:
          $ref: '#/definitions/Icon'
        type: array
        x-go-name: Icons
      message:
        description: the response message
        example: retrieved x icons
        type: string
        x-go-name: Message
      status:
        description: the status of the request
        example: success
        type: string
        x-go-name: Status
    type: object
    x-go-package: github.com/PrunedNeuron/Fluoride/docs/swagger
  Pack:
    description: Pack is the icon pack type
    properties:
      billing_status:
        description: Billing status
        example: billed
        type: string
        x-go-name: BillingStatus
      created_at:
        description: Date when the pack was added
        example: "2020-09-17T03:07:13.418204+05:30"
        format: date-time
        type: string
        x-go-name: CreatedAt
      developer_username:
        description: Icon pack developer username
        example: jdoe
        type: string
        x-go-name: DevUsername
      id:
        description: Icon pack ID
        example: 2
        format: int64
        type: integer
        x-go-name: ID
      name:
        description: Icon pack name
        example: Valacons
        type: string
        x-go-name: Name
      updated_at:
        description: Date when the pack was updated
        example: "2020-09-17T03:07:13.418204+05:30"
        format: date-time
        type: string
        x-go-name: UpdatedAt
      url:
        description: Icon pack url (play store)
        example: https://play.google.com
        type: string
        x-go-name: URL
    type: object
    x-go-package: github.com/PrunedNeuron/Fluoride/pkg/model
  PackRequest:
    description: PackRequest is the icon pack request
    properties:
      billing_status:
        description: billing status of the icon pack
        example: active
        type: string
        x-go-name: BillingStatus
      developer_username:
        description: username of the icon pack's developer
        example: ayush
        type: string
        x-go-name: DevUsername
      name:
        description: name of the icon pack
        example: Amphetamine
        type: string
        x-go-name: Name
      url:
        description: play store url of the icon pack
        example: https://play.google.com/store/apps/details?id=com.trello
        type: string
        x-go-name: URL
    type: object
    x-go-package: github.com/PrunedNeuron/Fluoride/docs/swagger
  PackResponse:
    description: PackResponse is the icon pack response
    properties:
      packs:
        description: the list of packs
        items:
          $ref: '#/definitions/Pack'
        type: array
        x-go-name: Packs
      status:
        description: the status of the request
        example: success
        type: string
        x-go-name: Status
    type: object
    x-go-package: github.com/PrunedNeuron/Fluoride/docs/swagger
  Plan:
    description: Plan is the plan type
    properties:
      billing_cycle:
        description: Billing cycle in days
        example: 30
        format: int64
        type: integer
        x-go-name: BillingCycle
      created_at:
        description: Date when the plan was added
        example: "2020-09-17T03:07:13.418204+05:30"
        format: date-time
        type: string
        x-go-name: CreatedAt
      description:
        description: Plan description
        example: Best suited for experienced icon pack devs.
        type: string
        x-go-name: Description
      id:
        description: Plan ID
        example: 5
        format: int64
        type: integer
        x-go-name: ID
      intro:
        description: Plan introduction
        example: Pro
        type: string
        x-go-name: Intro
      name:
        description: Plan name
        example: John Doe
        type: string
        x-go-name: Name
      price:
        description: Plan price per month
        example: $1.99
        type: string
        x-go-name: Price
      updated_at:
        description: Date when the plan was updated
        example: "2020-09-17T03:07:13.418204+05:30"
        format: date-time
        type: string
        x-go-name: UpdatedAt
    type: object
    x-go-package: github.com/PrunedNeuron/Fluoride/pkg/model
  User:
    description: User is the generic user type
    properties:
      created_at:
        description: Date when the User was added
        example: "2020-09-17T03:07:13.418204+05:30"
        format: date-time
        type: string
        x-go-name: CreatedAt
      email:
        description: User email
        example: jdoe@gmail.com
        type: string
        x-go-name: Email
      id:
        description: User ID
        example: 24
        format: int64
        type: integer
        x-go-name: ID
      name:
        description: User name
        example: John Doe
        type: string
        x-go-name: Name
      role:
        description: User role (admin | developer)
        example: developer
        type: string
        x-go-name: Role
      updated_at:
        description: Date when the User was updated
        example: "2020-09-17T03:07:13.418204+05:30"
        format: date-time
        type: string
        x-go-name: UpdatedAt
      url:
        description: User website
        example: https://jdoe.co
        type: string
        x-go-name: URL
      username:
        description: User username
        example: jdoe
        type: string
        x-go-name: Username
    type: object
    x-go-package: github.com/PrunedNeuron/Fluoride/pkg/model
host: localhost:3000
info:
  contact:
    email: am@ayushm.dev
    name: Ayush Mishra
    url: http://ayushm.dev
  description: This is the API documentation page for the backend API used by the fluoride icon pack management service. Feel free to try hitting the endpoints using the interactive interface provided by redoc.
  license:
    name: GPL 3
    url: https://opensource.org/licenses/gpl-3.0
  title: Fluoride, a robust icon pack management service.
  version: 0.0.1
paths:
  /developers:
    get:
      operationId: GetDevs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              developers:
                items:
                  $ref: '#/definitions/User'
                type: array
              status:
                description: status message
                example: success
                type: string
            type: object
      summary: Gets the list of all the developers present in the database.
      tags:
      - Users
    post:
      consumes:
      - application/json
      operationId: SaveDev
      parameters:
      - description: information about the new developer
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/DevRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              message:
                description: informational message
                example: successfully added developer
                type: string
              status:
                description: status message
                example: success
                type: string
            type: object
        "500":
          description: server error
          schema:
            properties:
              error:
                description: error message
                example: user may already exist
                type: string
              message:
                description: informational message
                example: invalid request
                type: string
              status:
                description: status message
                example: failure
                type: string
            type: object
      summary: Adds the given developer to the database.
      tags:
      - Users
  /developers/{developer}:
    get:
      operationId: GetDevByUsername
      parameters:
      - description: developer username
        in: path
        name: developer
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              developers:
                items:
                  $ref: '#/definitions/User'
                type: array
              status:
                description: status message
                example: success
                type: string
            type: object
      summary: Gets the developer with the given username.
      tags:
      - Users
  /developers/{developer}/packs:
    post:
      consumes:
      - application/json
      operationId: SavePack
      parameters:
      - description: username of the developer who owns the icon pack
        in: path
        name: developer
        required: true
        type: string
      - description: information about the new icon pack
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/PackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: server error
      summary: Adds the given icon pack to the database.
      tags:
      - IconPacks
  /developers/count:
    get:
      description: Gets the number of developers in the database
      operationId: GetDevCount
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              count:
                description: number of developers
                type: integer
              status:
                description: status message
                type: string
            type: object
      tags:
      - Users
  /icons:
    get:
      operationId: GetIcons
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/IconResponse'
            type: array
      summary: Gets the list of all the icon requests present in the database.
      tags:
      - IconRequests
  /packs:
    get:
      operationId: GetPacks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/PackResponse'
            type: array
      summary: Gets the list of all the icon packs present in the database.
      tags:
      - IconPacks
produces:
- application/json
schemes:
- http
- https
security:
- api_key: []
securityDefinitions:
  api_key:
    in: header
    name: X-API-KEY
    type: apiKey
swagger: "2.0"
