# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
    build:
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - setup_remote_docker: # (2)
                  version: 19.03.12
                  docker_layer_caching: true # (3)

            - restore_cache:
                  keys:
                      - go-mod-v1-{{ checksum "go.sum" }}
            - run:
                  name: Build using docker compose
                  command: |
                      set -x
                      COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
            - save_cache:
                  key: go-mod-v1-{{ checksum "go.sum" }}
                  paths:
                      - "/go/pkg/mod"
