name: Continuous Integration

on:
    push:
        branches:
            - development

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Build using compose
              run: docker-compose build
            - name: Run using compose
              run: docker-compose up
